(async function(){
  "use strict";
  var config, token, current, dirty=false;
  var sections=document.getElementById("sections"), form=document.getElementById("form"), status=document.getElementById("status"), frame=document.getElementById("frame"), title=document.getElementById("view-title");
  function say(message,error){status.textContent=message;status.style.color=error?"#9a271e":""}
  function mark(){dirty=true;say("عندك تغييرات مازال ما تحفظوش");}
  function esc(s){return String(s||"").replace(/[&<>\"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})}
  function nav(){sections.innerHTML="";Object.keys(config.sections).forEach(function(id){var b=document.createElement("button");b.textContent=config.sections[id].name||id;b.dataset.id=id;b.className=id===current?"active":"";b.onclick=function(){show(id)};sections.appendChild(b)})}
  function show(id){current=id;nav();var s=config.sections[id], node=document.getElementById("section-template").content.cloneNode(true);title.textContent=s.name||id;form.innerHTML="";form.appendChild(node);form.querySelectorAll("[data-field]").forEach(function(el){el.value=s[el.dataset.field]||"";el.oninput=function(){s[el.dataset.field]=el.value;mark();if(el.dataset.field==="name"){title.textContent=el.value;nav()}}});var tw=s.tweet||(s.tweet={});form.querySelectorAll("[data-tweet]").forEach(function(el){var key=el.dataset.tweet;if(el.type==="checkbox")el.checked=!!tw[key];else el.value=tw[key]||"";el.oninput=function(){tw[key]=el.type==="checkbox"?el.checked:el.value;mark()}})}
  function showTheme(){current="theme";nav();title.textContent="ألوان الموقع والزوايا";var t=config.theme;form.innerHTML='<div class="theme-grid">'+[["green","الأخضر"],["red","الأحمر"],["gold","الذهبي"],["panel","لون الصناديق"],["ink","لون الكتابة"]].map(function(x){return'<label>'+x[1]+'<input type="color" data-theme="'+x[0]+'" value="'+esc(t[x[0]])+'"></label>'}).join("")+'<label>استدارة الصناديق<input type="range" min="8" max="48" data-theme="radius" value="'+(t.radius||28)+'"><output>'+(t.radius||28)+'px</output></label></div>';form.querySelectorAll("[data-theme]").forEach(function(el){el.oninput=function(){t[el.dataset.theme]=el.type==="range"?Number(el.value):el.value;if(el.nextElementSibling)el.nextElementSibling.textContent=el.value+"px";mark()}})}
  function showBlocks(){current="blocks";nav();title.textContent="النصوص والصور داخل المقاطع";form.innerHTML="";form.appendChild(document.getElementById("block-template").content.cloneNode(true));var select=document.getElementById("block-select");Object.keys(config._blocks).forEach(function(key){var o=document.createElement("option");o.value=key;o.textContent=config._blocks[key].name||key;select.appendChild(o)});function load(){var key=select.value,b=config._blocks[key];form.querySelector('[data-block=eyebrow]').value=b.eyebrow||"";form.querySelector('[data-block=title]').value=b.title||"";form.querySelector('[data-block=body]').value=Array.isArray(b.body)?b.body.join("\n\n"):b.body||"";document.getElementById("image-path").value=(config.images&&config.images[key])||""}select.onchange=load;form.querySelectorAll("[data-block]").forEach(function(el){el.oninput=function(){var b=config._blocks[select.value],key=el.dataset.block;b[key]=key==="body"?el.value.split(/\n\s*\n/).filter(Boolean):el.value;mark()}});document.getElementById("image-path").oninput=function(){config.images=config.images||{};config.images[select.value]=this.value;mark()};document.getElementById("image-file").onchange=async function(){if(!this.files[0])return;try{say("كنرفع الصورة…");var file=this.files[0],r=await fetch("/api/upload",{method:"POST",headers:{"X-Editor-Token":token,"X-Slot":select.value,"X-Filename":file.name,"Content-Type":file.type||"application/octet-stream"},body:file});var data=await r.json();if(!r.ok)throw new Error(data.error);config.images=config.images||{};config.images[select.value]=data.path;document.getElementById("image-path").value=data.path;mark();say("الصورة ترفعات. دير حفظ باش تبان فالمعاينة") }catch(e){say(e.message,true)}};load()}
  async function post(path,body,headers){var r=await fetch(path,{method:"POST",headers:Object.assign({"X-Editor-Token":token,"Content-Type":"application/json"},headers||{}),body:body});var data=await r.json();if(!r.ok)throw new Error(data.error||"فشل الطلب");return data}
  document.querySelector("[data-view=theme]").onclick=showTheme;
  document.querySelector("[data-view=blocks]").onclick=showBlocks;
  document.getElementById("save").onclick=async function(){try{say("كنحفظ وكنبني المعاينة…");var r=await post("/api/save",JSON.stringify(config));dirty=false;say(r.message);frame.src="/preview/?v="+Date.now()}catch(e){say(e.message,true)}};
  document.getElementById("preview").onclick=function(){frame.scrollIntoView({behavior:"smooth"});frame.src="/preview/?v="+Date.now()};
  document.getElementById("publish").onclick=async function(){if(!confirm("واش متأكد بغيتي تحفظ، تدير commit، وتنشر التغييرات فـ main؟"))return;try{if(dirty)await post("/api/save",JSON.stringify(config));say("كننشر فـ GitHub…");var r=await post("/api/publish","{}");dirty=false;say(r.message)}catch(e){say(e.message,true)}};
  try{var r=await fetch("/api/config",{cache:"no-store"});config=await r.json();token=config._token;delete config._token;say(config._git?"كاينة تغييرات محلية قبل المحرر؛ النشر غادي يشملها":"المحرر واجد");current=Object.keys(config.sections)[0];nav();show(current)}catch(e){say("ما قدرناش نحملو الإعدادات: "+e.message,true)}
}());
